export const ERROR_MSG = {
  InvalidPin: "INVALID PIN",
  InvalidName: "INVALID NAME ",
  InvalidLength: "INVALID LENGTH ",
  InvalidEmail: "INVALID EMAIL ID",
  InvalidUsername: "INVALID FULL NAME",
  EnterEmail: "PLEASE ENTER EMAIL ID",
  InvalidCredentials: "INVALID CREDENTIAL ",
  SomethingWentWrong: "SOMETHING WENT WRONG",
  PasswordNotMatch: "PASSWORDS DONT MATCH",
  EnterPassword: "PLEASE ENTER PASSWORD",
  EmailAlreadyRegistered: "EMAIL ALREADY REGISTER ",
  NoInternet: "PLEASE CHECK YOUR INTERNET CONNECTION",
  PLEASE_ENTER_PASSWORD_AGAIN: "PLEASE ENTER PASSWORD AGAIN",
  Invalid_PSWD:
    "YOUR PASSWORD MUST BE AT LEAST 8 CHARACTERS LONG, CONTAINS AT LEAST 1 NUMBER AND MUST BE A MIXTURE OF UPPERCASE AND LOWERCASE LETTERS",
};
